export const GET_DEPARTMENTS_BY_STORE_ID = 'boilerplate/reportShiftFrequency/GET_DEPARTMENTS_BY_STORE_ID';
export const GET_DEPARTMENTS_BY_STORE_ID_SUCCESS = 'boilerplate/reportShiftFrequency/GET_DEPARTMENTS_BY_STORE_ID_SUCCESS';
export const GET_DEPARTMENTS_BY_STORE_ID_ERROR = 'boilerplate/reportShiftFrequency/GET_DEPARTMENTS_BY_STORE_ID_ERROR';

export const GET_REPORT_SHIFT_FREQUENCY = 'boilerplate/reportShiftFrequency/GET_REPORT_SHIFT_FREQUENCY_ID';
export const GET_REPORT_SHIFT_FREQUENCY_SUCCESS = 'boilerplate/reportShiftFrequency/GET_REPORT_SHIFT_FREQUENCY_SUCCESS';
export const GET_REPORT_SHIFT_FREQUENCY_ERROR = 'boilerplate/reportShiftFrequency/GET_REPORT_SHIFT_FREQUENCY_ERROR';

export const CHANGE_SEARCH_OPTIONS = 'boilerplate/reportShiftFrequency/CHANGE_SEARCH_OPTIONS';
